### ISSUE TITLE
erroneous Error message when using using stream-mode 

### ISSUE THREAD

**Issue by fullofentropy** [german-st/node-red-contrib-sharepoint#1]
node-red version: v0.20.8
Functionality still works well.  Receive error when clicking the deploy button.

Configuration
node-red-contrib-sharepoint installed
URL service field left blank (since it is being supplied by the functional node)
supply a msg.spURL from functional node.
Click deploy and receive the following message.

Is there an easy quick way to turn off/disable the trigger for this configuration error whenever I click the deploy button?

![image](https://user-images.githubusercontent.com/7788850/66703546-6353b780-ecd9-11e9-89ee-760e02bb5a0c.png)

**Comment by german-st** [comment]
[https://github.com/german-st/node-red-contrib-sharepoint/pull/2](url)
